// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nadvxvuwblgtkyvicvhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZHZ4dnV3YmxndGt5dmljdmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDEwNTYsImV4cCI6MjA2ODkxNzA1Nn0.Td3xqU9REXCR-q2EgnHzUknF_CjKueZ6m2N_oWnNcws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});